# Generated by Django 4.1.2 on 2022-10-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="original_price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product", name="selling_price", field=models.IntegerField(),
        ),
    ]
